// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using flashcard_backend_api.Data;

#nullable disable

namespace flashcard_backend_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("flashcard.Shared.Models.Flashcard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Flashcards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1d1a1b1-c1d1-e1f1-0123-456789abcdef"),
                            Answer = "Paris",
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Question = "What is the capital of France?"
                        },
                        new
                        {
                            Id = new Guid("d2e2f2b2-c2d2-e2f2-5678-90abcdef0123"),
                            Answer = "Jupiter",
                            CreatedDate = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Question = "What is the largest planet in our solar system?"
                        },
                        new
                        {
                            Id = new Guid("e3f3a3b3-c3d3-e3f3-abcd-012345abcdef"),
                            Answer = "William Shakespeare",
                            CreatedDate = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Question = "Who wrote 'Romeo and Juliet'?"
                        },
                        new
                        {
                            Id = new Guid("f4a4a4b4-c4d4-e4f4-7890-123456abcdef"),
                            Answer = "Au",
                            CreatedDate = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Question = "What is the chemical symbol for gold?"
                        },
                        new
                        {
                            Id = new Guid("a5b5c5d5-e5f5-4321-8901-234567abcdef"),
                            Answer = "1945",
                            CreatedDate = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Question = "In what year did World War II end?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
